[package]
name = "tiny-raytracer"
version = "0.1.0"
authors = ["Le_Charooo <Raphaelmoralibigras@outook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
